#!/bin/bash
# bash minidlna 192.168.111.7
docker run -d --net=host \
--name minidlna \
-v /storage/dlna/:/media \
-e MINIDLNA_MEDIA_DIR=/media \
-e MINIDLNA_LISTENING_IP=$1 \
-e MINIDLNA_PORT=8200 \
-e MINIDLNA_FRIENDLY_NAME=$HOSTNAME bobrik/minidlna
