#!/bin/bash
docker run -d --net=host \
--name minidlna \
-v /media/storage-00/dlna:/media \
-e MINIDLNA_MEDIA_DIR=/media \
-e MINIDLNA_LISTENING_IP=192.168.111.251 \
-e MINIDLNA_PORT=8200 \
-e MINIDLNA_FRIENDLY_NAME=vostro.home.jab bobrik/minidlna
