#!/bin/bash
# bash transmission 192.168.111.14 /storage/dlna/
docker run -ti \
--name transmission-pessoal -p $1:9091:9091 \
-v $2:/var/lib/transmission-daemon/downloads/ \
-e TRUSER=admin -e TRPASSWD='VuDa2204adm' \
dperson/transmission
