#!/bin/bash
# funcao de descoberta do sistema operacional
# get_so -s (retorna o sistema operasional)
# get_so -v (versao do sistema)
get_so(){
        while test -n "$1"
        do
        case $1 in
                -s | --operatingsystem)
                        grep PRETTY_NAME= /etc/os-release | cut -d \" -f 2 | awk '{print $1}'
                ;;
                -v | --version)
                        grep VERSION_ID= /etc/os-release | cut -d \" -f2
                ;;
                *) echo "opcao invalida"
        esac
        shift
        done
}

if_centos(){
tee /etc/yum.repos.d/docker.repo <<-'EOF'
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF
	yum install docker-engine -y
}

if_rhel(){
	subscription-manager repos --enable=rhel-7-server-extras-rpms
	yum install docker -y
}

if_ubuntu(){
	apt-get install apt-transport-https ca-certificates curl software-properties-common -y
	echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && apt-key fingerprint 0EBFCD88

	apt-get update
	apt-get purge lxc-docker -y
	apt-get install docker-ce -y
}

case `get_so -s` in
	Ubuntu|elementary) if_ubuntu ;;
	CentOS) if_centos ;;
	Red) if_rhel ;;
esac

systemctl enable docker
systemctl restart docker
groupadd docker
echo "gpasswd -a nariga docker"
