#!/bin/bash
# funcao de descoberta do sistema operacional
# get_so -s (retorna o sistema operasional)
# get_so -v (versao do sistema)
get_so(){
        while test -n "$1"
        do
        case $1 in
                -s | --operatingsystem)
                        grep PRETTY_NAME= /etc/os-release | cut -d \" -f 2 | awk '{print $1}'
                ;;
                -v | --version)
                        grep VERSION_ID= /etc/os-release | cut -d \" -f2
                ;;
                *) echo "opcao invalida"
        esac
        shift
        done
}

if_centos(){
	yum install -y yum-utils lvm2 \
		device-mapper-persistent-data

	yum-config-manager --add-repo \
		https://download.docker.com/linux/centos/docker-ce.repo

	yum-config-manager --enable docker-ce-edge
	yum install docker-ce -y
}

if_rhel(){
	subscription-manager repos --enable=rhel-7-server-extras-rpms
	yum install docker -y
}

if_ubuntu(){
	apt-get install apt-transport-https ca-certificates curl software-properties-common -y
	echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && apt-key fingerprint 0EBFCD88

	apt-get update
	apt-get purge lxc-docker -y
	apt-get install docker-ce -y
}

case `get_so -s` in
	Ubuntu|elementary) if_ubuntu ;;
	CentOS) if_centos ;;
	Red) if_rhel ;;
esac

systemctl enable docker
systemctl restart docker
groupadd docker
echo "gpasswd -a nariga docker"

curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
