#!/bin/bash
docker pull gitlab/gitlab-ee:latest
docker run --detach \
  --hostname gitlab.home.stc \
  --publish 192.168.111.101:443:443 --publish 192.168.111.101:80:80 --publish 192.168.111.101:22:22 \
  --name gitlab-linode \
  --restart always \
  --volume /srv/gitlab/config:/etc/gitlab \
  --volume /srv/gitlab/logs:/var/log/gitlab \
  --volume /srv/gitlab/data:/var/opt/gitlab \
  --env GITLAB_OMNIBUS_CONFIG="external_url 'https://gitlab.home.stc/';" \
  gitlab/gitlab-ee:latest
