#!/bin/bash
docker pull narigacdo/squid:gerenciado
docker run -ti -d --name proxy_squid \
	-v $PWD/$2:/etc/squid3/squid.conf \
	-v $PWD/AD:/etc/squid3/AD \
	-p $1:3128:3128 -p $1:80:80 \
	narigacdo/squid:gerenciado

msg_padrao="
\nEntre com o ip e arquivo de configuracao do squid
\nExemplo....
\n$0 192.168.0.8 squid.zerado
"
