#!/bin/bash
docker --version || {
	echo "Ver1ifique instalacao do docker"
	exit 1
}
curl --version || {
	echo "Verifique instalacao do curl"
	exit 1
}

docker-compose --version || {
	curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	chmod +x /usr/local/bin/docker-compose
}
docker-compose up -d
echo "Para remover:"
echo "docker-compose stop ; docker-compose rm"
